# Cloud Run service configuration for Suchi Web
# This file can be used with: gcloud run services update suchi-web --from-file=cloudrun-service.yaml

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: suchi-web
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 60
      containers:
      - image: REGION-docker.pkg.dev/PROJECT_ID/ARTIFACT_REGISTRY/suchi-web:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: VITE_API_URL
          value: "https://suchi-api-XXXXX.run.app/v1"
        resources:
          limits:
            cpu: "1000m"
            memory: 256Mi
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1











