import { Injectable } from "@nestjs/common";

interface ProposalSection {
  name: string;
  draftText: string;
  targetWords?: number;
  status?: string;
  gaps?: string[];
}

export interface FormattedDraft {
  subject: string;
  html: string;
  plain: string;
}

@Injectable()
export class DraftFormatterService {
  formatFellowshipDraft(params: {
    fellowshipName: string;
    opportunityId: string;
    proposalRunId: string;
    sections: ProposalSection[];
    originalSubject?: string;
  }): FormattedDraft {
    const subject = params.originalSubject
      ? `Re: ${params.originalSubject}`
      : `[Bodh AI] ${params.fellowshipName} — Draft Ready`;

    // Collect all gaps across sections
    const allGaps: string[] = [];
    for (const s of params.sections) {
      if (s.gaps && s.gaps.length > 0) {
        allGaps.push(...s.gaps.map((g) => `${g} (in ${s.name})`));
      }
    }

    // Build plain text
    const plainParts: string[] = [
      `${params.fellowshipName} — Draft Ready`,
      "",
    ];
    for (const s of params.sections) {
      const wordCount = s.draftText.split(/\s+/).length;
      const limitLabel = s.targetWords ? ` (${wordCount}/${s.targetWords} words)` : ` (${wordCount} words)`;
      plainParts.push(`${s.name}${limitLabel}`);
      plainParts.push("─".repeat(50));
      plainParts.push(s.draftText);
      plainParts.push("");
    }

    if (allGaps.length > 0) {
      plainParts.push("⚠ Gaps requiring manual input:");
      for (const gap of allGaps) {
        plainParts.push(`  - ${gap}`);
      }
      plainParts.push("");
    }

    plainParts.push("---");
    plainParts.push("Generated by Bodh AI Funding Bot");
    plainParts.push(`Opportunity: ${params.opportunityId} | Run: ${params.proposalRunId}`);

    const plain = plainParts.join("\n");

    // Build HTML
    const htmlSections = params.sections
      .map((s) => {
        const wordCount = s.draftText.split(/\s+/).length;
        const limitLabel = s.targetWords ? `${wordCount}/${s.targetWords} words` : `${wordCount} words`;
        const escapedText = this.escapeHtml(s.draftText).replace(/\n/g, "<br>");
        return `
          <h3 style="color:#1a1a1a;border-bottom:1px solid #ddd;padding-bottom:4px;">${this.escapeHtml(s.name)} <span style="color:#888;font-weight:normal;font-size:0.85em">(${limitLabel})</span></h3>
          <div style="font-size:14px;line-height:1.6;color:#333;margin-bottom:24px;">${escapedText}</div>`;
      })
      .join("\n");

    const gapsHtml = allGaps.length > 0
      ? `<div style="background:#fff3cd;border:1px solid #ffc107;border-radius:4px;padding:12px;margin:16px 0;">
          <strong>⚠ Gaps requiring manual input:</strong>
          <ul style="margin:8px 0 0;">${allGaps.map((g) => `<li>${this.escapeHtml(g)}</li>`).join("")}</ul>
        </div>`
      : "";

    const html = `
      <div style="font-family:Georgia,'Times New Roman',serif;max-width:700px;margin:0 auto;">
        <h2 style="color:#1a1a1a;">${this.escapeHtml(params.fellowshipName)} — Draft Ready</h2>
        ${htmlSections}
        ${gapsHtml}
        <hr style="border:none;border-top:1px solid #ddd;margin:24px 0;">
        <p style="font-size:12px;color:#888;">
          Generated by Bodh AI Funding Bot<br>
          Opportunity: ${this.escapeHtml(params.opportunityId)} | Run: ${this.escapeHtml(params.proposalRunId)}
        </p>
      </div>`;

    return { subject, html, plain };
  }

  formatProposalDraft(params: {
    proposalTitle: string;
    opportunityId: string;
    proposalRunId: string;
    sections: ProposalSection[];
    fitScore?: number;
    fitDecision?: string;
    originalSubject?: string;
  }): FormattedDraft {
    const subject = params.originalSubject
      ? `Re: ${params.originalSubject}`
      : `[Bodh AI] ${params.proposalTitle} — Draft Ready`;

    const fitLine = params.fitScore != null
      ? `Fit Score: ${params.fitScore}/100 (${params.fitDecision ?? "unknown"})`
      : "";

    const allGaps: string[] = [];
    for (const s of params.sections) {
      if (s.gaps && s.gaps.length > 0) {
        allGaps.push(...s.gaps.map((g) => `${g} (in ${s.name})`));
      }
    }

    const plainParts: string[] = [
      `${params.proposalTitle} — Draft Ready`,
      fitLine,
      "",
    ];
    for (const s of params.sections) {
      plainParts.push(s.name);
      plainParts.push("─".repeat(50));
      plainParts.push(s.draftText);
      plainParts.push("");
    }
    if (allGaps.length > 0) {
      plainParts.push("⚠ Gaps requiring manual input:");
      for (const gap of allGaps) plainParts.push(`  - ${gap}`);
      plainParts.push("");
    }
    plainParts.push("---");
    plainParts.push("Generated by Bodh AI Funding Bot");
    plainParts.push(`Opportunity: ${params.opportunityId} | Run: ${params.proposalRunId}`);

    return { subject, html: `<pre>${this.escapeHtml(plainParts.join("\n"))}</pre>`, plain: plainParts.join("\n") };
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");
  }
}
