steps:
  - name: "node:20"
    entrypoint: "bash"
    args:
      - "-lc"
      - |
        set -euo pipefail

        # Diagnostic: Confirm key is injected (length only, not the key)
        echo "=== DIAGNOSTIC: Secret Injection ==="
        if [ -n "$$DEEPSEEK_API_KEY" ]; then
          echo "DEEPSEEK_API_KEY is SET, length=$${#DEEPSEEK_API_KEY}"
        else
          echo "DEEPSEEK_API_KEY is NOT SET or empty"
        fi

        echo "=== Running Eval ==="
        cd eval
        npm ci
        npx ts-node cli.ts run \
          --cases cases/tier1/zero_citation_regression.yaml \
          --output reports/zero-citation-regression.json \
          --summary
    secretEnv: ["DEEPSEEK_API_KEY"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-lc"
      - |
        set -euo pipefail
        REPORT_PATH="/workspace/eval/reports/zero-citation-regression.json"
        DEST="gs://gen-lang-client-0202543132_cloudbuild/eval-reports/zero-citation-regression-${BUILD_ID}.json"
        if [ -f "$$REPORT_PATH" ]; then
          gsutil cp "$$REPORT_PATH" "$$DEST"
          echo "Report uploaded to: $$DEST"
        else
          echo "Report not found at $$REPORT_PATH"
        fi

availableSecrets:
  secretManager:
    - versionName: projects/gen-lang-client-0202543132/secrets/deepseek-api-key/versions/latest
      env: "DEEPSEEK_API_KEY"

options:
  logging: CLOUD_LOGGING_ONLY
timeout: "3600s"
