steps:
  - name: "node:20"
    entrypoint: "bash"
    args:
      - "-lc"
      - |
        set -euo pipefail

        # Diagnostic: Confirm key is injected (length only, not the key)
        echo "=== DIAGNOSTIC: Secret Injection ==="
        if [ -n "$$DEEPSEEK_API_KEY" ]; then
          echo "DEEPSEEK_API_KEY is SET, length=$${#DEEPSEEK_API_KEY}"
        else
          echo "DEEPSEEK_API_KEY is NOT SET or empty"
        fi

        # Diagnostic: Test Deepseek API with real key
        echo "=== DIAGNOSTIC: Deepseek API Auth Test ==="
        RESPONSE=$$(curl -sS -w "\nHTTP_CODE:%{http_code}" \
          -X POST https://api.deepseek.com/v1/chat/completions \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $$DEEPSEEK_API_KEY" \
          -d '{"model":"deepseek-chat","messages":[{"role":"user","content":"test"}],"max_tokens":5}')
        HTTP_CODE=$$(echo "$$RESPONSE" | grep -o 'HTTP_CODE:[0-9]*' | cut -d: -f2)
        echo "Deepseek API: HTTP $$HTTP_CODE"
        if [ "$$HTTP_CODE" = "200" ]; then
          echo "✓ Auth successful - key is valid"
        elif [ "$$HTTP_CODE" = "401" ]; then
          echo "✗ Auth failed (401) - key invalid or malformed"
        elif [ "$$HTTP_CODE" = "429" ]; then
          echo "⚠ Rate limited (429)"
        else
          echo "⚠ Unexpected response: $$HTTP_CODE"
        fi

        echo "=== Running Eval ==="
        cd eval
        npm ci
        npx ts-node cli.ts run \
          --cases cases/tier1/zero_citation_regression.yaml \
          --output reports/zero-citation-regression.json \
          --summary
    secretEnv: ["DEEPSEEK_API_KEY"]

availableSecrets:
  secretManager:
    - versionName: projects/gen-lang-client-0202543132/secrets/deepseek-api-key/versions/latest
      env: "DEEPSEEK_API_KEY"

options:
  logging: CLOUD_LOGGING_ONLY
timeout: "3600s"
